**Tensor**

In [ ]:
import numpy as np
import torch

In [ ]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [ ]:
type(x_data)

torch.Tensor

In [ ]:
arr=np.array(data)
arr

array([[1, 2],
       [3, 4]])

In [ ]:
x=torch.from_numpy(arr)
x

tensor([[1, 2],
        [3, 4]])

In [ ]:
x_ones= torch.ones_like(x)
x_ones

tensor([[1, 1],
        [1, 1]])

In [ ]:
x_zeros= torch.zeros_like(x)
x_zeros

tensor([[0, 0],
        [0, 0]])

In [ ]:
x_rand= torch.rand_like(x, dtype=torch.float)
x_rand

tensor([[0.2480, 0.9608],
        [0.9970, 0.1728]])

In [ ]:
rand_tensor= torch.rand(2,3)
rand_tensor

tensor([[0.8857, 0.9995, 0.5975],
        [0.8609, 0.2986, 0.7297]])

In [ ]:
ones_tensor= torch.ones(2,3, dtype=torch.float32)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
zeros_tensor= torch.zeros(2,3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
rand_tensor.shape

torch.Size([2, 3])

In [ ]:
rand_tensor.dtype

torch.float32

In [ ]:
rand_tensor.device

device(type='cpu')

In [ ]:
if torch.cuda.is_available():
    rand_tensor = rand_tensor.to('cuda')

In [ ]:
rand_tensor.device

device(type='cpu')

In [ ]:
 rand_tensor

tensor([[0.8857, 0.9995, 0.5975],
        [0.8609, 0.2986, 0.7297]])

In [ ]:
rand_tensor[:,1]=9
rand_tensor

tensor([[0.8857, 9.0000, 0.5975],
        [0.8609, 9.0000, 0.7297]])

In [ ]:
rand_tensor[0]

tensor([0.8857, 9.0000, 0.5975])

In [ ]:
rand_tensor[:,1]

tensor([9., 9.])

In [ ]:
rand_tensor[:,-1] # rand_tensor[...,-1]

tensor([0.5975, 0.7297])

In [ ]:
rand_tensor.sum()

tensor(21.0737)

In [ ]:
rand_tensor.sum().item()

21.07372283935547

In [ ]:
t1= torch.cat([rand_tensor, zeros_tensor],dim=1)
t1

tensor([[0.8857, 9.0000, 0.5975, 0.0000, 0.0000, 0.0000],
        [0.8609, 9.0000, 0.7297, 0.0000, 0.0000, 0.0000]])

In [ ]:
t1= torch.cat([rand_tensor, zeros_tensor],dim=0)
t1

tensor([[0.8857, 9.0000, 0.5975],
        [0.8609, 9.0000, 0.7297],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [ ]:
rand_tensor.mul(ones_tensor)

tensor([[0.8857, 9.0000, 0.5975],
        [0.8609, 9.0000, 0.7297]])

In [ ]:
rand_tensor.mul(zeros_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
rand_tensor

tensor([[0.8857, 9.0000, 0.5975],
        [0.8609, 9.0000, 0.7297]])

In [ ]:
rand_tensor.matmul(rand_tensor.T)

tensor([[82.1414, 82.1984],
        [82.1984, 82.2736]])

In [ ]:
rand_tensor.add_(5)

tensor([[ 5.8857, 14.0000,  5.5975],
        [ 5.8609, 14.0000,  5.7297]])

In [ ]:
n= np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [ ]:
t=torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [ ]:
t.add_(4)

tensor([5., 5., 5., 5., 5.], dtype=torch.float64)

In [ ]:
x = torch.empty(5)
print(x)

tensor([       nan, 7.0065e-45, 1.3593e-43, 1.4013e-43, 1.4013e-43])


In [ ]:
x.size()

torch.Size([5])

In [ ]:
x = torch.empty(2,3)
print(x)

tensor([[1.2342e+10, 3.1559e-41, 1.2963e+10],
        [3.1559e-41, 0.0000e+00, 0.0000e+00]])


In [ ]:
y=x.view(6)
y

tensor([1.2342e+10, 3.1559e-41, 1.2963e+10, 3.1559e-41, 0.0000e+00, 0.0000e+00])

In [ ]:
z=x.view(1,-1)
z

tensor([[1.2342e+10, 3.1559e-41, 1.2963e+10, 3.1559e-41, 0.0000e+00, 0.0000e+00]])

In [ ]:
a= torch.ones(2,2)
b= torch.ones(2,2)
a,b

(tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [ ]:
a+b,a-b,a*b,a/b

(tensor([[2., 2.],
         [2., 2.]]),
 tensor([[0., 0.],
         [0., 0.]]),
 tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [ ]:
a[0,1].item()

1.0

In [ ]:
torch.full((2,4),100)

tensor([[100, 100, 100, 100],
        [100, 100, 100, 100]])