In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr.ndim

1

In [ ]:
arr = np.array(42)
print(arr)

42


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=9)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[[[[[1 2 3 4]]]]]]]]]
number of dimensions : 9


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
print(arr[1,1,1])
print(arr[1][1][1])

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
5
5


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[ 2  3  4  5]
 [ 7  8  9 10]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[0:2, 2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[3 8]


In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(4, 2).base)

[1 2 3 4 5 6 7 8]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9,10,11,12])
newarr = arr.reshape(2, 3, -1)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-8)
print(newarr)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr = arr.reshape((4,3),axis=0)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr = np.array([1, 2, 3,4,5,6,7,8])
for x in arr:
  print(x,end=" ")

1 2 3 4 5 6 7 8 

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(x)

[1 2 3]
[1 2 3]
[1 2 3]
[4 5 6]
[4 5 6]
[4 5 6]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 2)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6]),)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(arr[x])

[1 3 5 7]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]]])
x = np.where(arr==11)
print(x)
print(arr[x])

(array([0]), array([3]), array([1]))
[11]


In [ ]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
arr = np.concatenate(arr)
print(arr)
print(np.sort(arr))

[3 2 4 5 0 1]
[0 1 2 3 4 5]
